# Generated by Django 4.1.7 on 2023-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(default=1, max_length=255, verbose_name='Режиссёры'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Directors',
        ),
    ]
