# Generated by Django 4.1.7 on 2023-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
