# Generated by Django 4.1.7 on 2023-02-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched',
        ),
    ]
