# Generated by Django 4.1.7 on 2023-02-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
    ]
