# Generated by Django 4.1.7 on 2023-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(default=1, max_length=3333),
            preserve_default=False,
        ),
    ]
